import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'userMenu',
        path: '',
        title: 'User Management',
        translateKey: 'nav.userMenu.userMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'userMenu.item1',
                path: '/new-user',
                title: 'New User',
                translateKey: 'nav.userMenu.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'userMenu.item2',
                path: '/approved-users',
                title: 'Approved Users',
                translateKey: 'nav.userMenu.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'productConsultationMenu',
        path: '',
        title: 'Product Consultation',
        translateKey: 'nav.productConsultationMenu.productConsultationMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'productConsultationMenu.item1',
                path: '/consultation/vehicle',
                title: 'Vehicle',
                translateKey: 'nav.productConsultationMenu.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'productConsultationMenu.item2',
                path: '/consultation/equipment',
                title: 'Equipment',
                translateKey: 'nav.productConsultationMenu.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'productConsultationMenu.item3',
                path: '/consultation/used-autoparts',
                title: 'Used Autoparts',
                translateKey: 'nav.productConsultationMenu.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'productManagementMenu',
        path: '',
        title: 'Product Management',
        translateKey: 'nav.productManagementMenu.productManagementMenu',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'productManagementMenu.item1',
                path: '/new-products',
                title: 'New Products',
                translateKey: 'nav.productManagementMenu.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'productManagementMenu.item2',
                path: '/approved-products',
                title: 'Approved Products',
                translateKey: 'nav.productManagementMenu.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'internalAuction',
        path: '',
        title: 'Internal Auction Handled bg NK',
        translateKey: 'nav.internalAuction.internalAuction',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'internalAuction.item1',
                path: '/auction-vehicle',
                title: 'Vehicle',
                translateKey: 'nav.internalAuction.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'internalAuction.item2',
                path: '/auction-equipment',
                title: 'Equipment',
                translateKey: 'nav.internalAuction.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'exportList',
        path: '',
        title: 'Export List',
        translateKey: 'nav.exportList.exportList',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'exportList.item1',
                path: '/export-vehicle',
                title: 'Vehicle',
                translateKey: 'nav.exportList.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'exportList.item2',
                path: '/export-equipment',
                title: 'Equipment',
                translateKey: 'nav.exportList.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'exportList.item3',
                path: '/export-used-autoparts',
                title: 'Used Autoparts',
                translateKey: 'nav.exportList.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'wantedItems',
        path: '',
        title: 'Wanted Items Management',
        translateKey: 'nav.wantedItems.wantedItems',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'wantedItems.item1',
                path: '/used-autoparts-request',
                title: 'Used Autoparts Request',
                translateKey: 'nav.wantedItems.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'newAutoparts',
        path: '',
        title: 'New Items Management',
        translateKey: 'nav.newAutoparts.newAutoparts',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'newAutoparts.item1',
                path: '/new-autoparts-request',
                title: 'New Autoparts Request',
                translateKey: 'nav.newAutoparts.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'expiredProducts',
        path: '',
        title: 'Expired Products',
        translateKey: 'nav.expiredProducts.expiredProducts',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'expiredProducts.item1',
                path: '/expired-products/vehicle',
                title: 'Vehicle',
                translateKey: 'nav.expiredProducts.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'expiredProducts.item2',
                path: '/expired-products/equipment',
                title: 'Equipment',
                translateKey: 'nav.expiredProducts.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'expiredProducts.item3',
                path: '/expired-products/used-autoparts',
                title: 'Used Autoparts',
                translateKey: 'nav.expiredProducts.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'soldout',
        path: '',
        title: 'Soldout',
        translateKey: 'nav.soldout.soldout',
        icon: 'collapseMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'soldout.item1',
                path: '/soldout/vehicle',
                title: 'Vehicle',
                translateKey: 'nav.soldout.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'soldout.item2',
                path: '/soldout/equipment',
                title: 'Equipment',
                translateKey: 'nav.soldout.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'soldout.item3',
                path: '/soldout/used-autoparts',
                title: 'Used Autoparts',
                translateKey: 'nav.soldout.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
